name: uuiz CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    name: Run zig build test on ubuntu-latest
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Install Zig
        uses: mlugg/setup-zig@v2

      - name: Verify Zig installation
        run: zig version

      - name: Run test
        run: zig build test
